version: '3'

services:
    catalog:
        image: postgres:10.12
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: https://raw.githubusercontent.com/irods/irods_testing_environment/main/projects/ubuntu-18.04/Dockerfile
        volumes:
            - "/tmp/mountdir:/wormhole:ro"
        depends_on:
            - catalog

    some-redis:
        image: redis

    ingest-worker:
        build:
            context: .
            dockerfile: Dockerfile.ingest_worker
        environment:
            IRODS_HOST: irods-catalog-provider
            IRODS_PORT: 1247
            IRODS_USER_NAME: rods
            IRODS_ZONE_NAME: tempZone
            IRODS_PASSWORD: rods
            CELERY_BROKER_URL: redis://some-redis:6379/0
        cap_add:
            - NET_ADMIN
        volumes:
            - "/tmp/mountdir:/wormhole:ro"
        depends_on:
            - some-redis
            - irods-catalog-provider
